name: Update KernelSU-Next Submodule

on:
  workflow_dispatch:

jobs:
  fix-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository (Without Submodules)
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Remove Old Submodule Traces
        run: |
          git rm --cached KernelSU
          rm -rf .git/modules/KernelSU
          rm -rf KernelSU

      - name: Re-Add Submodule
        run: |
          git submodule add --force https://github.com/rifsxd/KernelSU-Next.git KernelSU

      - name: Pull Latest Submodule
        run: |
          git submodule update --init --remote --recursive

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v6
